%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/nvidia/rgbd_dataset_freiburg1_xyz

# camera intrinsics
# fr1
camera.fx: 476.84
camera.fy: 476.72
camera.cx: 311.613040
camera.cy: 250.313989

# ueye
#camera.fx: 458.654
#camera.fy: 457.469215
#camera.cx: 367.643040
#camera.cy: 248.313989

camera.depth_scale: 5000

# VO Parameters
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 10
min_inliers: 30
keyframe_rotation: 0.1
keyframe_translation: 3
map_point_erase_ratio: 0.1

# VO Parameters
KeyFrameSize: 0.05
KeyFrameLineWidth: 1
GraphLineWidth: 0.9
PointSize:2
CameraSize: 0.8
CameraLineWidth: 3
ViewpointX: 0
ViewpointY: 0.1
ViewpointZ: -20.0
ViewpointF: 500
